name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up JDK 17 (required for AGP 8.5.0+)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Grant execute permission for Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Clean project (optional but recommended for CI)
      - name: Clean project
        run: ./gradlew clean

      # Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Run unit tests (optional but recommended)
      - name: Run Unit Tests
        run: ./gradlew test

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
